# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titile',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.URLField(blank=True),
        ),
    ]
