# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171126_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
