# Generated by Django 2.0 on 2017-12-11 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171212_0010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', ''), ('M', 'M'), ('F', 'F')], max_length=1, null=True),
        ),
    ]
