# Generated by Django 2.0 on 2017-12-16 08:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20171216_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Python3.6.3', 'Python3.6.3'), ('Django1.11', 'Django1.11'), ('Django2.0', 'Django2.0'), ('Nodejs', 'Nodejs'), ('jQuery', 'jQuery'), ('CSS', 'CSS'), ('Font-end', 'Font-end'), ('Back-end', 'Back-end'), ('Bootstrap', 'Bootstrap')], max_length=78, null=True),
        ),
    ]
