# Generated by Django 2.0 on 2017-12-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
