# Generated by Django 2.0.1 on 2018-01-08 18:39

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20171220_0114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Python3.6', 'Python3.6'), ('Django2.0', 'Django2.0'), ('Nodejs', 'Nodejs'), ('Javascript', 'Javascript'), ('CSS', 'CSS'), ('Font-end', 'Font-end'), ('Back-end', 'Back-end'), ('Bootstrap', 'Bootstrap')], max_length=69, null=True),
        ),
    ]
