# Generated by Django 2.0.1 on 2018-01-17 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20180109_0539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='create_time',
        ),
    ]
