# Generated by Django 2.0.1 on 2018-01-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180117_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
