# Generated by Django 2.0.1 on 2018-01-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_edit_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='create_time',
        ),
        migrations.AddField(
            model_name='comment',
            name='edit_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
